oname: Lesson 15 CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        run: grep -q "this will fail" app.txt

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Deploying application..."
